api/urls.py
from django.urls import path

from . import api

app_name = 'api'

urlpatterns = [
    path('users/', api.user_list, name='api-user-list'),

    path('movies/', api.movie_list, name='api-movie-list'),

    path('ratings/', api.rating_list, name='api-rating-list'),
]

coding_test_visionary/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('userauth/', include('userauth.urls')),
    path('movies/', include('movies.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('add/', views.add_movie, name='add'),
    path('<str:id>/', views.detail, name='detail'),
    path('<str:id>/edit/', views.edit_movie, name='edit'),
    path('<str:id>/delete/', views.delete_movie, name='delete'),
]

movies/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from userauth.models import User

import uuid
# Create your models here.
class GenreType(models.TextChoices):
    COMEDY = 'comedy', 'Comedy'
    ACTION = 'action', 'Action'
    CRIME = 'crime', 'Crime'

class RatingType(models.TextChoices):
    PG = 'pg', 'PG'
    R = 'r', 'R'

class Movie(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    name = models.CharField(max_length=255)
    genre = models.CharField(max_length=10, choices=GenreType.choices)
    rating = models.CharField(max_length=10, choices=RatingType.choices)
    release_date = models.DateField()

    image = models.ImageField(upload_to= 'images/movies/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='movies', blank=True, null=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def average_rating(self):
        ratings = self.ratings.all()

        if not ratings:
            return None
        
        total = sum(rating.rating for rating in ratings)
        count = ratings.count()

        return round(total/count, 2)

    def __str__(self):
        return self.name


class Rating(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    user_id = models.ForeignKey(User, related_name='ratings', blank=True, null=True, on_delete=models.SET_NULL)
    movie_id = models.ForeignKey(Movie, related_name='ratings', blank=True, null=True, on_delete=models.CASCADE)
    rating = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)])

    def __str__(self):
        return f'{self.user_id.name}-{self.rating}-{self.movie_id.name}'

movies/forms.py
from django import forms
from .models import Movie, Rating, GenreType, RatingType
from datetime import date

INPUT_CLASSES = 'w-full mb-4 py-4 px-6 rounded-xl text-gray-800 border'

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'genre', 'rating', 'release_date', 'image', 'description',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Name...',
            }),

            'genre': forms.Select(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Genre...',
            }),

            'rating': forms.Select(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rating...',
            }),

            'release_date': forms.DateInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Release Date...',
                'type': 'date'
            }),

            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            }),

            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Description...'
            }),
        }
    
    def clean(self):
        cleaned_data = super().clean()
        release_date = cleaned_data.get('release_date')

        if release_date > date.today():
           
            self.add_error('release_date', forms.ValidationError("Future date is not accepted."))
        
        return cleaned_data
    
class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('rating',)
        widgets = {
            'rating': forms.NumberInput(attrs={
                'class': 'w-40 py-2 px-6 rounded-xl bg-gray-700 text-white',
                'placeholder': 'Out of 5'
            })
        }

class MovieFilterForm(forms.Form):
    genre_types = forms.MultipleChoiceField(
        choices=GenreType.choices,
        widget=forms.CheckboxSelectMultiple(attrs={'onchange': 'this.form.submit();'}),
        required=False,
        label="Genre Types"
    )

    rating_types = forms.MultipleChoiceField(
        choices=RatingType.choices,
        widget=forms.CheckboxSelectMultiple(attrs={'onchange': 'this.form.submit();'}),
        required=False,
        label="Rating Types"
    )

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Movie
from .forms import MovieForm, RatingForm

# Create your views here.
def detail(request, id):
    movie = get_object_or_404(Movie, pk=id)

    if request.user.is_authenticated:
        is_rated = movie.ratings.filter(user_id=request.user).exists()
    else:
        is_rated = False

    if request.method == 'POST':
        form = RatingForm(request.POST)

        if form.is_valid():
            rating = form.save(commit=False)
            rating.user_id = request.user
            rating.movie_id = movie
            rating.save()

            messages.success(request, 'Rating is added.')
            return redirect('movies:detail', movie.id)
        
        else:
            messages.error(request, 'Rating failed.')

    else:
        form = RatingForm()

    return render(request, 'movies/detail.html', {
        'title': movie.name,
        'movie': movie,
        'form': form,
        'is_rated': is_rated or None
    })

@login_required
def add_movie(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)

        if form.is_valid():
            movie = form.save(commit=False)
            movie.created_by = request.user
            movie.save()

            messages.success(request, 'A movie is added.')

            return redirect('/')
        
    else:
        form = MovieForm()
    
    return render(request, 'movies/add.html', {
        'title': 'Add Movie',
        'form': form
    })

@login_required
def edit_movie(request, id):
    movie = get_object_or_404(Movie, pk=id)

    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES, instance=movie)

        if form.is_valid():
            form.save()

            messages.success(request, 'Details are updated.')
            return redirect('movies:detail', movie.id)
        
        else:
            messages.error(request, 'Update failed!')
        
    else:
        form = MovieForm(instance=movie)

    return render(request, 'movies/add.html', {
        'title': 'Edit Movie',
        'form': form
    })

@login_required
def delete_movie(request, id):
    movie = get_object_or_404(Movie, pk=id)
    movie.delete()

    messages.success(request, 'Movie has been deleted.')

    return redirect('core:home')
    

movies/templates/movies/add.html
{% extends 'base.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
<div class="w-1/2 my-auto mx-auto p-4 bg-slate-800 rounded-xl">
    <h1 class="mb-4 text-center text-3xl">{{ title }}</h1>

    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-2">
            <label class="inline-block mb-3">Name:</label><br>
            {{ form.name }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Genre:</label><br>
            {{ form.genre }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Rating:</label><br>
            {{ form.rating }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Release date:</label><br>
            {{ form.release_date }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Image:</label><br>
            {{ form.image }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Description:</label><br>
            {{ form.description }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-2 p-6 bg-red-300 text-gray-800 rounded-xl">  
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>  
        {% endif %}  

        <div class="flex justify-center items-center">
            <button class="w-20 text-center px-3 py-2 bg-gray-600 rounded-xl hover:bg-gray-700 transition ease-in-out duration-300">Add</button>
        </div>

    </form>
</div>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% load static movieextras %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="flex flex-col md:flex-row gap-5 justify-evenly">

        {% if movie.image %}
        <div class="w-full h-[600px] md:w-3/5 rounded-xl overflow-hidden border-8 border-cyan-950"> 
            <img src="{{ movie.image.url }}" class="w-full h-full object-cover">
        </div>
        {% else %}
        <div class="w-full h-[600px] md:w-3/5 rounded-xl overflow-hidden border-8 border-cyan-950"> 
            <h1 class="w-full h-full flex justify-center items-center text-gray-300">No image available</h1>
        </div>
        {% endif %}

        <div class="w-full md:w-2/5 flex flex-col justify-between p-6 bg-cyan-950 rounded-xl space-y-3">
            <h2 class="text-2xl font-semibold text-cyan-500">{{ movie.name }}</h2>
            <p class="text-xl">Genre: {{ movie.genre|upper }}</p>
            <p class="text-xl">Movie Type: {{ movie.rating|upper }}</p>
            <p class="text-xl">Release Date: {{ movie.release_date }}</p>
            <p class="text-xl">Rating: {{ movie.average_rating|stars|safe }} ({{ movie.average_rating }})</p>

        {% if request.user.is_authenticated %}

        {% if movie.created_by == request.user %}
            <a href="{% url 'movies:edit' movie.id %}" class="w-max mt-6 px-6 py-1 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition duration-300 ease-in-out">Edit</a>
            <a href="{% url 'movies:delete' movie.id %}" class="w-max mt-6 px-6 py-1 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700 transition duration-300 ease-in-out">Delete</a>
        {% else %}
            
            {% if is_rated %}
            <p class="text-2xl">User has already rated this movie once.</p>
            {% else %}
            <form action="." method="post" class="bottom-0">
                {% csrf_token %}
        
                <div class="mb-4 flex items-center justify-between">
                    <p class="text-xl">Rate this movie: </p>
                    
                    {{ form.rating }}
                </div>

                {% if form.errors or form.non_field_errors %}
                    <div class="mb-2 p-6 bg-red-300 text-gray-800 rounded-xl">  
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
        
                        {{ form.non_field_errors }}
                    </div>  
                {% endif %}  
        
                <div class="mt-3 flex justify-center items-center">
                    <button class="w-20 text-center px-3 py-2 bg-gray-600 rounded-xl hover:bg-gray-700 transition ease-in-out duration-300">Rate</button>
                </div>
        
            </form>
            {% endif %}

        {% endif %}

        {% else %}
            <h1 class="mt-5 text-xl font-bold text-cyan-500">Please log in to edit, delete and rate movies!!</h1>
        {% endif %}
        </div>
    </div>
    
    <div class="mt-6 p-6 bg-cyan-950 rounded-xl">
        <h1 class="mb-5 text-xl">Description:</h1>
        {% if movie.description %}
        <p class="text-lg">{{ movie.description }}</p>
        {% else %}
        <p class="text-lg">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deserunt eius officia placeat, molestias aperiam accusantium beatae laudantium eos nemo modi. Quibusdam ipsa ex perferendis velit optio aspernatur eius delectus. Dignissimos?</p>
        {% endif %}
    </div>
{% endblock %}