api/urls.py
from django.urls import path

from . import api

app_name = 'api'

urlpatterns = [
    path('users/', api.user_list, name='api-user-list'),

    path('movies/', api.movie_list, name='api-movie-list'),

    path('ratings/', api.rating_list, name='api-rating-list'),
]

coding_test_visionary/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('userauth/', include('userauth.urls')),
    path('movies/', include('movies.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('add/', views.add_movie, name='add'),
    path('<str:id>/', views.detail, name='detail'),
    path('<str:id>/edit/', views.edit_movie, name='edit'),
    path('<str:id>/delete/', views.delete_movie, name='delete'),
]

userauth/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authViews
from .forms import LoginForm

app_name = 'userauth'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    
    path('login/', authViews.LoginView.as_view(
        template_name = 'userauth/login.html',
        authentication_form = LoginForm
    ), name='login'),

    path('logout/', authViews.LogoutView.as_view(), name='logout'),

]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.db.models import Q
from movies.models import Movie
from movies.forms import MovieFilterForm

# Create your views here.
def home(request):
    movies = Movie.objects.all().order_by('-created_at')
    query = request.GET.get('query', '')
    form = MovieFilterForm(request.GET)

    if form.is_valid():
        genre_types = form.cleaned_data['genre_types']
        rating_types = form.cleaned_data['rating_types']

        if genre_types:
            for genre in genre_types:
                movies = movies.filter(genre=genre)
    
        if rating_types:
            for rating in rating_types:
                movies = movies.filter(rating=rating)
            
    if query:
        movies = movies.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'core/home.html', {
        'title': 'Home Page',
        'movies': movies,
        'form': form,
        'query': query
    })

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}  {% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'src/styles.css' %}">
        {% block style %}{% endblock %}
    </head>

    <body class="w-screen text-white bg-slate-800">

        <div class="p-2">

            <nav class="w-4/5 mx-auto mt-2 px-3 py-3 flex justify-between items-center rounded-full shadow-2xl bg-gradient-to-bl from-gray-700 to-slate-800">
                
                <div class="pl-6">
                    <a href="{% url 'core:home' %}"  class="text-xl text-slate-400 font-semibold">Visionary Tech - Test</a>
                </div>    

                <div class="flex items-center space-x-4">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'movies:add' %}" class="inline-block text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Add Movie</a>
                        <a href="{% url 'userauth:logout' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Logout</a>
                    {% else %}
                        <a href="{% url 'userauth:signup' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Signup</a>
                        <a href="{% url 'userauth:login' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Login</a>
                    {% endif %}
                </div>
            </nav>

            {% if messages %}
                <div class="message w-max mx-auto mt-4 px-10 py-2 text-center bg-slate-800 rounded-full shadow-2xl">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            
        </div>

        <main class="max-w-6xl mx-auto p-6">
            {% block content %}

            {% endblock %}
        </main>

    </body>

</html>